exports.auth = require('./authController')
exports.home = require('./homeController')
exports.report = require('./reportController')
exports.kategori = require('./kategoriController')
exports.unit = require('./unitController')